### ISSUE TITLE
Error when adding tickets, no Assignee and not synced tickets

### ISSUE THREAD

**Issue by levikszabo** [chefsplate/groove-to-helpscout-migration-tool#6]
Hi!

First of all: awesome tool! Thank you very much!

Unfortunately after syncing customers we failed to sync tickets.
There are several error messages (2-3/10) like this:

`Failed to create HelpScout thread for Groove message (http://api.groovehq.com/v1/messages/9474824274 created by  at 2017-12-05T11:08:38Z, ticket #31986). Message was: 
No author defined for Groove link: http://api.groovehq.com/v1/agents/czpetra@gmail.com
Failed to create HelpScout thread for Groove message (http://api.groovehq.com/v1/messages/9702994442 created by  at 2017-12-05T09:22:25Z, ticket #31986). Message was: 
No author defined for Groove link: http://api.groovehq.com/v1/agents/czpetra@gmail.com
Failed to create HelpScout thread for Groove message (http://api.groovehq.com/v1/messages/4481823798 created by erikacostner@gmail.hu at 2017-12-05T10:59:16Z, ticket #31986). Message was: 
No recipient defined for Groove link: http://api.groovehq.com/v1/agents/czpetra@gmail.com
Failed to create HelpScout thread for Groove message (http://api.groovehq.com/v1/messages/9448904642 created by erikacostner@gmail.hu at 2017-12-05T04:03:32Z, ticket #31986). Message was: 
No recipient defined for Groove link: http://api.groovehq.com/v1/agents/czpetra@gmail.com
Failed to create HelpScout thread for Groove message (http://api.groovehq.com/v1/messages/5141269252 created by  at 2017-11-15T10:22:32Z, ticket #31986). Message was: 
No author defined for Groove link: http://api.groovehq.com/v1/agents/czpetra@gmail.com
Error encountered for ticket #35462 "Empty": Undefined offset: 0
Kérdés esetén kéjük vegye fel a kapcsolatot ügyfélszolgálati munkatársainkkal. Hívjon az alábbi számon: + 36 (1) 371 22 2...": Undefined offset: 0
Error encountered for ticket #35165 "Empty": Undefined offset: 0`

Any ideas? I saw you had an issue with this but that has a PR so it should be solved. We also don't have assignees even for the correctly synced tickets either...

**Comment by levikszabo** [comment]
It also seems that it does not insert any of the replies, just the first email.

**Comment by davidchchang** [comment]
Hey there, thanks for using our tool! It's been a very long time since I've used this ETL tool so I've forgotten how most of it works unfortunately (it has been a couple of years already)!

Taking a closer look, it seems most of the errors are because of `No <author/recipient> defined for Groove link`- we throw that exception on this line: https://github.com/chefsplate/groove-to-helpscout-migration-tool/blob/master/app/Console/Commands/Processors/TicketProcessor.php#L222

It looks like the API URL that you're accessing Groove with is http://api.groovehq.com/v1/, but that line is expecting HTTPS (e.g. https://api.groovehq.com/v1/)

I'll make a quick patch to master to fix this issue.

**Comment by davidchchang** [comment]
I've updated the ticket processor to support non-HTTPS Groove links for agent and attachments. Please let me know if this solves your issue!

**Comment by levikszabo** [comment]
Yup, it worked! In the meantime we identified the issue as well and it was simple enough for us to solve. Worked like a charm, thanks again for building this awesome tool :)

Üdv,
K.Szabó Levente

**Comment by davidchchang** [comment]
No problem, and glad it worked! Will close out the ticket for now. 

Cheers!
